//
//  expo_gliph_player.h
//
//  Master header matching the pod's module name (dashes -> underscores).
//  Xcode's Swift-generated interop header (expo_gliph_player-Swift.h) hardcodes
//  a self-import of <expo_gliph_player/expo_gliph_player.h> for any module that
//  has DEFINES_MODULE = YES and contains Swift — this file only needs to EXIST
//  under that exact name for the build to find it.
//
//  IMPORTANT: do NOT re-export GliphAudioPlayer.h from here (e.g. via
//  `#import "GliphAudioPlayer.h"`). The authoritative Objective-C interface
//  for the Swift `GliphAudioPlayer` class is auto-generated by the Swift
//  compiler itself, inside expo_gliph_player-Swift.h. GliphPlayerModule.mm
//  imports that generated header directly. If this file also pulls in a
//  second, hand-written declaration of the same class name, both end up in
//  the same translation unit and the build fails with:
//  "Duplicate interface definition for class 'GliphAudioPlayer'"
//  (which in turn cascades into unrelated-looking parse errors later in
//  GliphPlayerModule.mm, since Clang's parser gets confused after the
//  redefinition).
//
#import <Foundation/Foundation.h>
